# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: harshit16
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: taxwebmain
# "service" is the name of this project. This will also be added to your AWS resource names.
service: taxwebmain

provider:
  name: aws
  runtime: nodejs20.x
  
package:
  individually: true

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
# Enable ESBuild
esbuild:
  bundle: true
  minify: true
  sourcemap: true
  target: 'node20'
  platform: 'node'
  concurrency: 10
plugins:
  - serverless-offline